name: Build pull request to the master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the selected branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # set default directory
    defaults:
      run:
        working-directory: ./genesis-frontend
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use Node.j ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install
      - name: Run unit tests
        run: npm run test:ci
      - name: Run linters
        run: npm run lint
      - name: Build project
        run: npm run build
